api/urls.py
from django.urls import path, include
from rest_framework import routers
from rest_framework.authtoken import views

from api.API.resources import GenreViewSet, HallViewSet, MovieViewSet, OrderViewSet, UserViewSet
from api.API.resources import MovieSessionViewSet, MovieSessionSettingsViewSet

router = routers.SimpleRouter()
router.register(r'genres', GenreViewSet)
router.register(r'halls', HallViewSet)
router.register(r'movies', MovieViewSet)
router.register(r'sessions', MovieSessionViewSet)
router.register(r'sessionsettings', MovieSessionSettingsViewSet)
router.register(r'orders', OrderViewSet)
router.register(r'users', UserViewSet)


urlpatterns = [
    path('generate-token/', views.obtain_auth_token),
    path('', include(router.urls)),
]

moviehouse/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from moviehouse import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cinema.urls')),
    path('staff/', include('staff.urls')),
    path('api/', include('api.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

cinema/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models import CASCADE
from django.utils import timezone


AGE_CHOICES = (
    (1, 'all'),
    (2, '13+'),
    (3, '18+')
)


class Genre(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=300, unique=True)
    genres = models.ManyToManyField(Genre)
    description = models.TextField()
    director = models.CharField(max_length=100)
    starring = models.CharField(max_length=300)
    trailer = models.CharField(max_length=300, blank=True, null=True)
    teaser = models.CharField(max_length=300, blank=True, null=True)
    img_landscape = models.ImageField(upload_to='img/%Y/%m/%d', blank=True, null=True)
    img_standard = models.ImageField(upload_to='img/%Y/%m/%d', blank=True, null=True)
    img_small = models.ImageField(upload_to='img/%Y/%m/%d', blank=True, null=True)
    age_policy = models.PositiveSmallIntegerField(choices=AGE_CHOICES, default=1)
    advertised = models.BooleanField(default=False)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title


class Hall(models.Model):
    name = models.CharField(max_length=100, unique=True)
    sits_rows = models.PositiveSmallIntegerField(validators=[MinValueValidator(1)])
    sits_cols = models.PositiveSmallIntegerField(validators=[MinValueValidator(1)])

    @property
    def hall_capacity(self):
        return self.sits_cols * self.sits_rows

    def __str__(self):
        return f'{self.name} {self.hall_capacity} sits'


class MovieSession(models.Model):
    settings = models.ForeignKey('MovieSessionSettings', on_delete=CASCADE)
    date = models.DateField()

    class Meta:
        ordering = ['date']

    @property
    def free_sits(self):
        return Sit.objects.filter(session=self, order__isnull=True)

    @property
    def free_sits_number(self):
        return len(self.free_sits)

    @property
    def sold(self):
         return self.settings.hall.hall_capacity - self.free_sits_number

    def __str__(self):
        return f'{self.settings.hall.name}: {self.date} ' \
               f'{self.settings.time_start} - "{self.settings.movie.title[:20]}..."'


class MovieSessionSettings(models.Model):
    hall = models.ForeignKey(Hall, on_delete=CASCADE)
    movie = models.ForeignKey(Movie, on_delete=CASCADE)
    date_start = models.DateField(default=timezone.now)
    date_end = models.DateField()
    time_start = models.TimeField()
    time_end = models.TimeField()
    price = models.PositiveSmallIntegerField(validators=[MinValueValidator(1)])

    class Meta:
        ordering = ['-date_start']

    def save(self, **kwargs):
        if self.id:
            MovieSession.objects.filter(settings=self).delete()
        super().save(**kwargs)
        delta = self.date_end - self.date_start
        for day in range(delta.days + 1):
            session = MovieSession.objects.create(settings=self, date=self.date_start + timezone.timedelta(days=day))
            seats = []
            for sit in range(1, self.hall.hall_capacity + 1):
                seats.append(Sit(session=session, number=sit))
            Sit.objects.bulk_create(seats)

    def __str__(self):
        return f'{self.movie} ({self.hall.name}) {self.date_start} to ' \
               f'{self.date_end} ({self.time_start}-{self.time_end}) {self.price}$'



class CinemaUser(AbstractUser):
    email = models.EmailField(max_length=150, blank=False, unique=True)
    first_name = models.CharField(max_length=150, blank=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    class Meta:
        app_label = 'cinema'

    def __str__(self):
        return f'{self.first_name or self.email}'


class Order(models.Model):
    customer = models.ForeignKey(CinemaUser, on_delete=CASCADE)
    datetime = models.DateTimeField(auto_now=True)
    sits = models.ForeignKey('Sit', on_delete=CASCADE)

    class Meta:
        ordering = ['datetime']

    def __str__(self):
        return f'{self.customer} #{self.sits.number} for {self.datetime}'


class Sit(models.Model):
    session = models.ForeignKey(MovieSession, on_delete=CASCADE)
    number = models.PositiveSmallIntegerField(validators=[MinValueValidator(1)])

    class Meta:
        unique_together = ['session', 'number']

templates/account.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<section>
  <div class="container" data-aos="fade-up">
    <div class="row">
      <div class="col-lg-12 text-center mb-5">
        <h1 class="page-title">My account</h1>
      </div>
    </div>

    <div class="row mb-5">

      <div class="d-md-flex post-entry-2 half">
        <a href="#" class="me-4 thumbnail">
          <img src="{% static '/img/account.png' %}" alt="" class="img-fluid">
        </a>
        <div class="ps-md-5 mt-4 mt-md-0">

            <div class="row justify-content-center mt-5">

              <div class="col-lg-12">
                <h5 class="comment-title">logined as {{ user.first_name }}</h5>
                <hr>
                <div class="row">

                  <p>{{sum.sits__session__settings__price__sum}}$ TOTAL amount spent<br>
                     {{count}} pcs tickets were bought</p>

                  {% if recent_orders %}
                  <hr>
                  <div>
                  <h5 class="comment-title">Recently ordered tickets:</h5>
                  <table class="table">
                      <tbody>
                        {% for order in recent_orders %}
                        <tr class="bg-info">
                          <td scope="row"><a href="{% url 'session' order.sits.session.pk %}">{% if today == order.sits.session.date %}today,<br>{{order.sits.session.settings.time_start|date:'G:i'}}{% else %}{{order.sits.session.date|date:'M.j,Y'}}{% endif %}</a></td>
                          <td><font color="{{order.sits.session.settings.hall.name}}">{{order.sits.session.settings.hall.name|upper}}</font></td>
                          <td><a href="{% url 'movie' order.sits.session.settings.movie.pk %}">{{order.sits.session.settings.movie.title}}</a></td>
                          <td>{{order.sits.session.settings.price}}$</td>
                          <td><button type="button" class="btn btn-outline-secondary" style="width:40px;" disabled>{{order.sits.number}}</button></td>
                        </tr>
                        {% endfor %}
                      </tbody>
                  </table>
                  </div>
                  <hr>
                  {% endif %}


                   <table class="table">
                      <thead class="thead-light">
                        <tr>
                          <th scope="col">show</th>
                          <th scope="col">hall</th>
                          <th scope="col">movie</th>
                          <th scope="col">price</th>
                          <th scope="col">sit</th>
                        </tr>
                      </thead>

                      <tbody>
                        {% for order in orders %}
                        <tr
                         {% if today == order.sits.session.date %}class="table-success"{% endif %}
                         {% if today < order.sits.session.date %} class="table-info"{% endif %}>
                        <td scope="row"><a href="{% url 'session' order.sits.session.pk %}">{% if today == order.sits.session.date %}today,<br>{{order.sits.session.settings.time_start|date:'G:i'}}{% else %}{{order.sits.session.date|date:'M.j,Y'}}{% endif %}</a></td>
                          <td><font color="{{order.sits.session.settings.hall.name}}">{{order.sits.session.settings.hall.name|upper}}</font></td>
                          <td><a href="{% url 'movie' order.sits.session.settings.movie.pk %}">{{order.sits.session.settings.movie.title}}</a></td>
                          <td>{{order.sits.session.settings.price}}$</td>
                          <td><button type="button" class="btn btn-outline-secondary"  style="width:40px;" disabled>{{order.sits.number}}</button></td>
                        </tr>
                        {% endfor %}
                      </tbody>
                   </table>
                  {% include 'pagination.html' %}







                </div>
              </div>
            </div>
        </div>
      </div>



    </div>

  </div>
</section>


{% endblock %}

templates/admin.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<section>

  <div class="container" data-aos="fade-up">
    <div class="row">
      <div class="col-lg-12 text-center mb-5">
        <h1 class="page-title">Admin page</h1>
      </div>
    </div>

    <div class="row mb-5">

      <div class="d-md-flex post-entry-2 half">
        <div class="ps-md-5 mt-4 mt-md-0">
          <div class="post-meta mt-4">Manage:</div>

           <ul>
               <li><a href="{% url 'genre' %}">Genres</a></li>
               <li><a href="{% url 'hall' %}">Halls</a></li>
               <li><a href="{% url 'movies' %}">Movies</a></li>
               <li><a href="{% url 'settings-list' %}">Sessions settings</a></li>
               <li><a href="{% url 'sessions-list' %}">Sessions</a></li>
           </ul>



      </div>


      </div>

    </div>


  </div>
</section>

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">


<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>{{title}}</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static '/img/favicon.png' %}" rel="icon">

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:wght@400;500&family=Inter:wght@400;500&family=Playfair+Display:ital,wght@0,400;0,700;1,400;1,700&display=swap"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static '/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static '/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static '/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
    <link href="{% static '/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static '/vendor/aos/aos.css' %}" rel="stylesheet">

    <!-- Template Main CSS Files -->
    <link href="{% static '/css/variables.css' %}" rel="stylesheet">
    <link href="{% static '/css/main.css' %}" rel="stylesheet">

</head>

<body>


<!-- ======= Header ======= -->
<header id="header" class="header d-flex align-items-center fixed-top">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">


        <a href="{% url 'index' %}" class="logo d-flex align-items-center">
            <img src="{% static '/img/logo.png' %}" alt="">
            <h1>cinema</h1>
        </a>


        <nav id="navbar" class="navbar">
            <ul>
                {% if request.user.is_superuser %}
                <li>admin: {{ user.email }}</li>
                <li class="dropdown"><a href="{% url 'main' %}"><span>Admin menu</span> <i
                        class="bi bi-chevron-down dropdown-indicator"></i></a>
                    <ul>
                        <li><a href="{% url 'genre' %}">Genres</a></li>
                        <li><a href="{% url 'hall' %}">Halls</a></li>
                        <li><a href="{% url 'allmovies' %}">Movies</a></li>
                        <li><a href="{% url 'settings-list' %}">Session settings</a></li>
                        <li><a href="{% url 'sessions-list' %}">Sessions</a></li>
                    </ul>
                </li>
                {% endif %}
                {% if not request.user.is_superuser %}
                <li><a href="{% url 'index' %}">Home</a></li>
                <li><a href="{% url 'schedule' %}">Schedule</a></li>

                <!--          <li class="dropdown"><a href="category.html"><span>Categories</span> <i class="bi bi-chevron-down dropdown-indicator"></i></a>-->
                <!--            <ul>-->
                <!--              <li><a href="search-result.html">Search Result</a></li>-->
                <!--              <li><a href="#">Drop Down 1</a></li>-->
                <!--              <li class="dropdown"><a href="#"><span>Deep Drop Down</span> <i class="bi bi-chevron-down dropdown-indicator"></i></a>-->
                <!--                <ul>-->
                <!--                  <li><a href="#">Deep Drop Down 1</a></li>-->
                <!--                  <li><a href="#">Deep Drop Down 2</a></li>-->
                <!--                  <li><a href="#">Deep Drop Down 3</a></li>-->
                <!--                  <li><a href="#">Deep Drop Down 4</a></li>-->
                <!--                  <li><a href="#">Deep Drop Down 5</a></li>-->
                <!--                </ul>-->
                <!--              </li>-->
                <!--              <li><a href="#">Drop Down 2</a></li>-->
                <!--              <li><a href="#">Drop Down 3</a></li>-->
                <!--              <li><a href="#">Drop Down 4</a></li>-->
                <!--            </ul>-->
                <!--          </li>-->

                <li><a href="{% url 'about' %}">About</a></li>
                <li><a href="{% url 'contact' %}">Contacts</a></li>
                {% endif %}
                {% if user.is_authenticated %}
                <li class="dropdown"><a href={% url 'account' %}><span>my ACCOUNT</span> <i
                        class="bi bi-chevron-down dropdown-indicator"></i></a>
                    <ul>
                        <li><a href="{% url 'account' %}">ACCOUNT</a></li>
                        <li><a href="{% url 'logout' %}">logout</a></li>
                    </ul>
                </li>
                {% else %}
                <li class="dropdown"><a href={% url 'login' %}><span>enter ACCOUNT</span> <i
                        class="bi bi-chevron-down dropdown-indicator"></i></a>
                    <ul>
                        <li><a href="{% url 'login' %}">login</a></li>
                        <li><a href="{% url 'register' %}">register</a></li>
                    </ul>
                </li>
                {% endif %}
            </ul>
        </nav><!-- .navbar -->

        <div class="position-relative">
            <a href="#" class="mx-2"><span class="bi-facebook"></span></a>
            <a href="#" class="mx-2"><span class="bi-twitter"></span></a>
            <a href="#" class="mx-2"><span class="bi-instagram"></span></a>
            <a href="#" class="mx-2 js-search-open"> <!--<span class="bi-search"></span>--></a>
            <i class="bi bi-list mobile-nav-toggle"></i>

            <!-- ======= Search Form ======= -->
            <div class="search-form-wrap js-search-form-wrap">
                <form action="search-result.html" class="search-form">
                    <span class="icon bi-search"></span>
                    <input type="text" placeholder="Search" class="form-control">
                    <button class="btn js-search-close"><span class="bi-x"></span></button>
                </form>
            </div><!-- End Search Form -->

        </div>

    </div>

</header><!-- End Header -->


<main id="main">


    {% if messages %}
    {% for message in messages %}
    <div class="
                 {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %} alert-success {% endif %}
                 {% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %} alert-warning {% endif %}
                 {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %} alert-danger {% endif %}
                  alert alert-dismissible fade show" role="alert">
        <p>{{ message }}</p>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}


    {% block content %}

    {% endblock %}
</main><!-- End #main -->


<!-- ======= Footer ======= -->
<footer id="footer" class="footer">


    <div class="footer-content">

        <div class="container">
            <div class="row g-5">
                {% if not request.user.is_superuser %}
                <div class="col-lg-4">
                    <h3 class="footer-heading">About "Popcorn cinema"</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam ab, perspiciatis beatae autem
                        deleniti voluptate nulla a dolores, exercitationem eveniet libero laudantium recusandae officiis
                        qui aliquid blanditiis omnis quae. Explicabo?</p>
                    <p><a href="{% url 'about' %}" class="footer-link-more">Learn More</a></p>
                </div>
                <div class="col-6 col-lg-2">
                    <h3 class="footer-heading">Navigation</h3>
                    <ul class="footer-links list-unstyled">
                        <li><a href="{% url 'index' %}"><i class="bi bi-chevron-right"></i> Home</a></li>
                        <li><a href="{% url 'schedule' %}"><i class="bi bi-chevron-right"></i> Schedule</a></li>
                        <li><a href="{% url 'contact' %}"><i class="bi bi-chevron-right"></i> Contact</a></li>
                        <li><a href="{% url 'about' %}"><i class="bi bi-chevron-right"></i> About us</a></li>
                        <li><a href="{% url 'account' %}"><i class="bi bi-chevron-right"></i> Account</a></li>
                    </ul>
                </div>
                {% endif %}


                <div class="col-lg-4">
                    <h3 class="footer-heading">Now Playing (4):</h3>
                    <div class="spinner-grow text-success" role="status">
                        <span class="visually-hidden">Loading...</span>
                    </div>

                    <ul class="footer-links footer-blog-entry list-unstyled">
                        <li>
                            <a href="" class="d-flex align-items-center">
                                <img src="{% static '/img/post-sq-1.jpg' %}" alt="" class="img-fluid me-3">
                                <div>
                                    <div class="post-meta d-block"><span class="date">Comedy</span> <span class="mx-1">&bullet;</span>
                                        <span>Aug 20th '22 - Aug 24th '22</span></div>
                                    <div id="sessions">Minions: the raise of Gru</div>
                                </div>
                            </a>
                        </li>
                    </ul>

                </div>
            </div>
        </div>
    </div>

    <div class="footer-legal">
        <div class="container">

            <div class="row justify-content-between">
                <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                    <div class="copyright">
                        © Copyright <strong><span>Popcorn cinema</span></strong>. All Rights Reserved
                    </div>
                    <div class="credits">
                        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
                    </div>

                </div>

                <div class="col-md-6">
                    <div class="social-links mb-3 mb-lg-0 text-center text-md-end">
                        <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                        <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                        <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                    </div>

                </div>

            </div>
        </div>
    </div>


</footer>

<a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

<!-- Vendor JS Files -->
<script src="{% static '/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static '/vendor/swiper/swiper-bundle.min.js' %}"></script>
<script src="{% static '/vendor/glightbox/js/glightbox.min.js' %}"></script>
<script src="{% static '/vendor/aos/aos.js' %}"></script>

<!-- Template Main JS File -->
<script src="{% static '/js/main.js' %}"></script>

</body>

</html>

templates/contact.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

    <section id="contact" class="contact mb-5">
      <div class="container" data-aos="fade-up">

        <div class="row">
          <div class="col-lg-12 text-center mb-5">
            <h1 class="page-title">Contact us</h1>
          </div>
        </div>

        <div class="row gy-4">

          <div class="col-md-4">
            <div class="info-item">
              <i class="bi bi-geo-alt"></i>
              <h3>Address</h3>
              <address>34 W 13th St, New York, NY 10011, USA</address>
            </div>
          </div><!-- End Info Item -->

          <div class="col-md-4">
            <div class="info-item info-item-borders">
              <i class="bi bi-phone"></i>
              <h3>Phone Number</h3>
              <p><a href="tel:+12122552243">+1 (212) 2552243</a></p>
            </div>
          </div><!-- End Info Item -->

          <div class="col-md-4">
            <div class="info-item">
              <i class="bi bi-envelope"></i>
              <h3>Email</h3>
              <p><a href="mailto:info@quadcinema.com">info@quadcinema.com</a></p>
            </div>
          </div><!-- End Info Item -->

        </div>
          <br>

          <div id="map-container-google-1" class="z-depth-1-half map-container" style="height: 500px">
            <iframe src="https://maps.google.com/maps?q=Quad+Cinema&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0"
              style="border:0" allowfullscreen></iframe>
          </div>

      </div>
    </section>

  </main><!-- End #main -->

{% endblock %}

templates/movie.html
{% extends 'base.html' %}
{% block content %}

<section class="movie-content">
  <div class="container">
    <div class="row">
      <div class="col-md-9 post-content" data-aos="fade-up">

        <!-- ======= Single Post Content ======= -->
        <div class="movie">
            <div class="post-meta"><span class="date">{% for genre in movie.genres.all %} {{genre}} / {% endfor %}</span>  <!--  <span class="mx-1">&bullet;</span> <span>Jul 5th '22</span>--> </div>
          <h1 class="mb-5">{{object.title}}</h1>

          <figure class="my-4">
            {% if object.img_standard %}
            <img src="{{object.img_standard.url}}" alt="" class="img-fluid"  width="900" height="571">
            {% endif %}
            <figcaption>STARRING: {{object.starring}}</figcaption>
            <figcaption>DIRECTOR: {{object.director}}</figcaption>
            <figcaption>AGE POLICY: {{object.get_age_policy_display}}</figcaption>
          </figure>

          <p><span class="firstcharacter">{{object.description|make_list|first}}</span>{{object.description|make_list|slice:'1:'|join:''|linebreaks}}</p>

          <br>

        {% if all_sessions %}
        <div class="aside-block">
          <h3 class="aside-title">all sessions:</h3>
          <ul class="aside-tags list-unstyled">
                {% for session in all_sessions %}
                  <li><a href="{% url 'session' session.pk %}">{{session.date|date:'M d'}} {{session.settings.time_start|date:'H:i'}}</a></li>
                {% endfor %}
          </ul>
        </div><!-- End Tags -->
        {% endif %}

        </div><!-- End Single Post Content -->


      </div>
      <div class="col-md-3">
        <!-- ======= Sidebar ======= -->

        {% if today_sessions or tomorrow_sessions %}
        <div class="aside-block">
          <h3 class="aside-title">Sessions</h3>
          <ul class="aside-tags list-unstyled">
                {% if today_sessions %}
                  <p>today</p>
                  {% for session in today_sessions %}
                    <li><a href="{% url 'session' session.pk %}">{{session.settings.time_start}}</a></li>
                  {% endfor %}
                {% endif %}
                {% if tomorrow_sessions %}
                  <p>tomorrow</p>
                  {% for session in tomorrow_sessions %}
                    <li><a href="{% url 'session' session.pk %}">{{session.settings.time_start}}</a></li>
                  {% endfor %}
                {% endif %}
          </ul>
        </div><!-- End sessions -->
        {% endif %}



        <div class="aside-block">
          <h3 class="aside-title">Trailer</h3>
          <div class="video-post">
            <a href="{{ object.trailer }}" class="glightbox link-video">
              <span class="bi-play-fill"></span>
              <img src="https://img.youtube.com/vi/{{ object.trailer|slice:'17:' }}/sddefault.jpg" alt="" class="img-fluid">
            </a>
          </div>
        </div><!-- End Trailer -->

        <div class="aside-block">
          <h3 class="aside-title">Tieser</h3>
          <div class="video-post">
            <a href="{{ object.teaser }}" class="glightbox link-video">
              <span class="bi-play-fill"></span>
              <img src="https://img.youtube.com/vi/{{ object.teaser|slice:'17:' }}/sddefault.jpg" alt="" class="img-fluid">
            </a>
          </div>
        </div><!-- End Tieser -->


      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/pagination.html
{% if page_obj.paginator.num_pages > 1 %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endif %}

<!--<nav>-->
<!--  <ul class="pagination">-->
<!--    <li class="page-item disabled">-->
<!--      <a class="page-link" href="#" tabindex="-1">Previous</a>-->
<!--    </li>-->
<!--    <li class="page-item"><a class="page-link" href="#">1</a></li>-->
<!--    <li class="page-item active">-->
<!--      <a class="page-link" href="#">2 <span class="sr-only">(current)</span></a>-->
<!--    </li>-->
<!--    <li class="page-item"><a class="page-link" href="#">3</a></li>-->
<!--    <li class="page-item">-->
<!--      <a class="page-link" href="#">Next</a>-->
<!--    </li>-->
<!--  </ul>-->
<!--</nav>-->

templates/staff-movie-list.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

{% load crispy_forms_tags %}

<section>

  <div class="container" data-aos="fade-up">
    <div class="row">
      <div class="col-lg-12 text-center mb-5">
        <h1 class="page-title">Movies management</h1>
      </div>
    </div>

    <div class="row mb-5">

      <div class="d-md-flex post-entry-2 half">
        <div class="ps-md-5 mt-4 mt-md-0">
          <div class="post-meta mt-4">Movies</div>

          <div>
               <table class="table">
                  <thead class="thead-light">
                    <tr>
                      <th scope="col">id</th>
                      <th scope="col"></th>
                      <th scope="col">title</th>
                      <th scope="col">description</th>
                      <th scope="col">genres</th>
                      <th scope="col">director</th>
                      <th scope="col">starring</th>
                      <th scope="col">age</th>
                      <th scope="col"></th>
                      <th scope="col"></th>
                    </tr>
                  </thead>

                  <tbody>
                    {% for movie in object_list %}
                    <tr>
                      <th scope="row">{{movie.pk}}</th>
                      <td>{% if movie.img_small %}<img src="{{movie.img_small.url}}" width="182" height="136">{% endif %}</td>
                      <td>{{movie.title}}</td>
                      <td>{{movie.description|truncatechars:20}}</td>
                      <td>{% for genre in movie.genres.all %} {{genre}} {% endfor %}</td>
                      <td>{{movie.director}}</td>
                      <td>{{movie.starring}}</td>
                      <td>{{movie.get_age_policy_display}}</td>
                      <td>{% if not movie in ordered %}<a href="{% url 'movie-edit' movie.pk %}" class="btn btn-sm btn-warning">update</a>{% endif %}</td>
                      <td>
                          {% if not movie in ordered %}
                          <form method="post" action="{% url 'movie-delete' movie.pk %}">
                              {% csrf_token %}
                              <input type="hidden" name="pk" value="{{movie.pk}}">
                              <button type="delete" class="btn btn-sm btn-danger">delete</button>
                          </form>
                          {% endif %}
                      </td>
                    </tr>
                    {% endfor %}

                  </tbody>
               </table>


                <a href="{% url 'movie-create' %}"><button type='submit' class='btn btn-success'>add new</button></a>


          </div>

      </div>


      </div>

    </div>


  </div>
</section>

{% endblock %}